### ISSUE TITLE
Refining Vision Processing & Incorporating Topics

### ISSUE THREAD

**Issue by LuisC18** [OSU-AIMS/tic-tac-toe#7] opened 2021-08-09 14:46 UTC
We've been trying to find the best way to use the image topics the realsense-ros launch files publish. The image\color\raw.. topic would be useful to be able to grab from for a simple current frame the camera sees or for a live feed. The problem arises with the Ros limitations of only being able to have one node per script. Since the moveManipulator node is always active for any robot motion, creating another node for the image topic subscriber isn't possible in the same script.

**Comment by LuisC18** [comment] 2021-08-09 17:46
Possible solutions:
1. Use subprocess.call on an image topic subscriber to overwrite a local image file to load from whenever needed.
2. Reorganize script/ros structure to do all work with topics apart from script with the moveManipulator node. Output final movement information to a text file/.npy that the movement script loads and executes.

**Comment by acbuynak** [comment] 2021-08-26 02:24
Only partially understanding the root issue here, but I believe the changes made in https://github.com/OSU-AIMS/tic-tac-toe/commit/a914b0a78f720338d8adc737e1ba9b30f7822a78 demonstrate the ability of a node to sub/pub to multiple topics. 

The mentioned commit was only tested on a static image, but should transition easily to a live camera feed. I'm interested to see what the feedrate looks like considering (1) this is all in Python and (2) the nested scripts the image processing relies upon.

---

I believe further development is needed for the [nodes/board_tf_publisher.py](https://github.com/OSU-AIMS/tic-tac-toe/blob/TheGame/nodes/board_tf_publisher.py) in regards to the image processing and generally to finish the refactor. The structure is there now, just need to fix the annotations and clean the image-processing calls up.

**Comment by acbuynak** [comment] 2021-08-26 19:18
**Update:**
 Connected the iRS camera via USB3 card & cables. There does not seem to be any significant latency issue as the bandwidth is averaging `29.98 +/- .02 Hz`. This is the same as the `color/image_raw` data stream coming out of the iRS camera. Thus no load is noticeable on quick inspection.

@LuisC18 There seems to be an issue with the contour detection program. I'm unfamiliar with how your code works, but the current output seems statically display the number grid. Unknown whats the cause.

![image](https://user-images.githubusercontent.com/44533530/131023082-d23ed4cc-95ad-4304-9801-c08304cf1a49.png)

**Comment by acbuynak** [comment] 2022-01-25 23:17
Progress is continuing on this as the project is being refactored.

Ref Commits: f2f36098dc6742bb0f1427c7b61899a890de1ac0 0bfd416fd4b338b08700f4a6a87d7b642d236ab9

This issue to be resolved by upcoming refactor PR.

**Closed as completed** 2022-02-28 20:28 UTC

**Comment by LuisC18** [comment] 2022-02-28 20:42
Issue resolved by understanding ROS node structure. Every publisher has it's own node ([circle finder publisher example](https://github.com/OSU-AIMS/tic-tac-toe/blob/26235595e2607c869141c79f6887237d69929c1e/nodes/circle_state_publisher.py#L288))  and the master TTT script has its own [node](https://github.com/OSU-AIMS/tic-tac-toe/blob/26235595e2607c869141c79f6887237d69929c1e/scripts/tictactoe.py#L31).
